### PR TITLE
docs: make warning more direct

### PR DESCRIPTION
**Pull request by elharo**
@codyoss

### CODE REVIEW

**Comment by codyoss** [comment]
This file is autogenerated based off of the public discovery doc spec. Once changes are rolled out this code will be automatically updated.

**Comment by elharo** [comment]
so where is the public discovery doc spec?

**Comment by codyoss** [comment]
After changes are made internally things will propagate out to the public endpoint: https://dataflow.googleapis.com/$discovery/rest?version=v1b3

**Comment by elharo** [comment]
Can you be specific? Which file where is the source of this? (I wish we didn't check generated code into repos...)

**Comment by codyoss** [comment]
Messaged back directly.

**Pull request closed without merging**
