### PR TITLE
fix: don't use markdown style links

### PR DESCRIPTION
**Pull request by codyoss**
Fixes: #712

### CODE REVIEW

**Comment by codyoss** [comment]
Another option here is we could turn something like `This is [really important](http://example.com/important)` into `This is really important(See http://example.com/important)`. Thoughts?

**Comment by codyoss** [comment]
Note manual changes are only in gen.go and gen_test.go.

**Review by tbpg — COMMENTED** [review]
I think the links are useful. So, it seems sad to just remove them?

**Comment by codyoss** [comment]
I hear you, WDYT about the "( See http://example.com approach)"?

**Comment by tbpg** [comment]
Could we do `This is really important (http://example.com/important) stuff.`?

**Review by tbpg — APPROVED** [review]

**Pull request merged**
