### PR TITLE
feat(storagetransfer): Support FederatedIdentifyConfig for Azure Blob Storage

### PR DESCRIPTION
**Pull request by venky999**
Storage Transfer Service: Support FederatedIdentifyConfig for Azure Blob Storage

### CODE REVIEW

**Comment by codyoss** [comment]
These files are pulled from the public discovery doc listing -- we do not allow hand editing them. Please make a request to the API service if you wish to see a feature added to a service.

**Comment by venky999** [comment]
> These files are pulled from the public discovery doc listing -- we do not allow hand editing them. Please make a request to the API service if you wish to see a feature added to a service.

@codyoss May I know where the go api is .. because the api reference here https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storagetransfer/resource_storage_transfer_job.go.tmpl#L18

**Comment by codyoss** [comment]
This file is a cached version of what is being served at: https://storagetransfer.googleapis.com/$discovery/rest?version=v1

If there you think there is something missing from this definition it is best to reach out to that teams support page: https://cloud.google.com/storage-transfer/docs/support. This repo just generates clients from the public spec.

**Comment by venky999** [comment]
Thank you @codyoss I see the API is missing this feature but I am not sure how to raise the support

**Pull request closed without merging**
