### PR TITLE
option: change WithGRPCDialOption to get options as arguments

### PR DESCRIPTION
**Pull request by mookjp**
This is no big change but it would be easy to understand to take options as arguments, IMO

If you have any design thoughts here, please tell me about that!

### CODE REVIEW

**Comment by codyoss** [comment]
Hey, could you please open up an issue for discussing this feature request?

**Comment by mookjp** [comment]
@codyoss Sorry, I created: #608

**Comment by codyoss** [comment]
No worries, in general we just like to talk things through before we consider making changes 😄

**Comment by codyoss** [comment]
See comments on issue.

**Pull request closed without merging**
